<?php

namespace Boutique\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{	
    public function getArticlesForSearch( $search, $offset = 0, $limit = 0 ) {
        $qb = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('article')
                ->from('BoutiqueDatabaseBundle:Article', 'article')
                ->where("article.libelle LIKE '%".$search."%'")
                ->orWhere("article.code LIKE '%".$search."%'")
                //->orWhere("article.codeFournisseur LIKE '%".$search."%'")
                ->orWhere("article.description LIKE '%".$search."%'")
                ->setFirstResult($offset)
                ->setMaxResults($limit);

        //var_dump($qb->getQuery()->getSQL()); exit;

        $data = $qb->getQuery()->getResult();

        return $data;
    }
    
    public function getLastCode() {
        $qb = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('article.code')
                ->from('BoutiqueDatabaseBundle:Article', 'article')
                ->orderBy("article.id", "DESC");
        $data = $qb->getQuery()->getArrayResult();

        return (isset($data[0]))?$data[0]['code']:null;
    }
}