<?php

namespace Boutique\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{	
	public function getClientsForSearch( $search, $offset = 0, $limit = 0 ) {
		$qb = $this->getEntityManager()
			->createQueryBuilder()
			->select('client')
			->from('BoutiqueDatabaseBundle:Client', 'client')
			->where("client.nom LIKE '%".$search."%'")
                        ->orWhere("client.prenom LIKE '%".$search."%'")
                        ->orWhere("client.mail LIKE '%".$search."%'");
			//->setFirstResult($offset)
			//->setMaxResults($limit);
                
                //var_dump($qb->getQuery()->getSQL()); exit;
			
		$data = $qb->getQuery()->getResult();
		
		return $data;
	}
}