<?php

namespace Boutique\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends EntityRepository
{	
    public function getFacturesFilter( $year, $month  ) {
        $qb = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('f, (SELECT count(fa.id) FROM BoutiqueDatabaseBundle:FactureArticle fa WHERE fa.facture = f.id) AS articles')
                ->from('BoutiqueDatabaseBundle:Facture', 'f');
        
        if( !is_null($month) and !is_null($year) ) {
            $qb->where("f.dateCreation LIKE '".$year."-".$month."%'");
        }
        else if ( !is_null($month) and is_null($year) ) {
            $qb->where("f.dateCreation LIKE '%-".$month."%'");
        }
        else if ( is_null($month) and !is_null($year) ) {
            $qb->where("f.dateCreation LIKE '".$year."-%'");
        }
                
            $qb->orderBy('f.dateCreation', 'DESC');

        $data = $qb->getQuery();
        
        return $data;
    }
}