parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: GestionStock
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: f581d2a3a5531beb2f8220b64c59dd655500bc79
    database_path: null
    
knp_paginator:
    page_range: 10
    template:        
        pagination: BoutiqueGestionStockBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
