boutique_configuration:
    resource: "@BoutiqueConfigurationBundle/Resources/config/routing.yml"
    prefix:   /

#site_presentation:
#    resource: "@SitePresentationBundle/Resources/config/routing.yml"
#    prefix:   /

boutique_gestion_stock:
    resource: "@BoutiqueGestionStockBundle/Resources/config/routing.yml"
    prefix:   /


# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
