admin_home:
    pattern: /
    defaults: { _controller: BoutiqueGestionStockBundle:Home:index }
    
general_search:
    pattern: /search
    defaults: { _controller: BoutiqueGestionStockBundle:Home:rechercheGenerale, _method: post }

boutique_database_article:
    resource: "@BoutiqueGestionStockBundle/Resources/config/routing/article.yml"
    prefix:   /article

boutique_database_stock:
    resource: "@BoutiqueGestionStockBundle/Resources/config/routing/stock.yml"
    prefix:   /stock

boutique_database_facture:
    resource: "@BoutiqueGestionStockBundle/Resources/config/routing/facture.yml"
    prefix:   /facture
    
boutique_database_client:
    resource: "@BoutiqueGestionStockBundle/Resources/config/routing/client.yml"
    prefix:   /client
    
boutique_database_fournisseur:
    resource: "@BoutiqueGestionStockBundle/Resources/config/routing/fournisseur.yml"
    prefix:   /fournisseur