article:
  pattern: /
  defaults: { _controller: BoutiqueDatabaseBundle:Article:index }

article_show:
  pattern:  /{id}/show
  defaults: { _controller: BoutiqueDatabaseBundle:Article:show }

article_new:
  pattern: /new
  defaults: { _controller: BoutiqueDatabaseBundle:Article:new }

article_create:
  pattern: /create
  defaults: { _controller: BoutiqueDatabaseBundle:Article:create, _method: post }

article_edit:
  pattern: /{id}/edit
  defaults: { _controller: BoutiqueDatabaseBundle:Article:edit }

article_update:
  pattern: /{id}/update
  defaults: { _controller: BoutiqueDatabaseBundle:Article:update, _method: post }

article_delete:
  pattern: /{id}/delete
  defaults: { _controller: BoutiqueDatabaseBundle:Article:delete, _method: post }
  
article_search:
  pattern: /search
  defaults: { _controller: BoutiqueDatabaseBundle:Article:search }
