stock_new:
  pattern: /new_stock
  defaults: { _controller: BoutiqueDatabaseBundle:Stock:newStock }
  
stock_add:
  pattern: /{id_article}/add_stock
  defaults: { _controller: BoutiqueDatabaseBundle:Stock:addStock }

stock_create:
  pattern: /{id_article}/create_stock
  defaults: { _controller: BoutiqueDatabaseBundle:Stock:createStock }