facture:
  pattern: /
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:indexFacture }

facture_show:
  pattern: /{id}/show
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:showFacture }
  
facture_new:
  pattern: /new
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:newFacture }

facture_edit:
  pattern: /{id}/edit
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:editFacture }

facture_delete:
  pattern: /{id}/delete
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:deleteFacture }
  
facture_article_search:
  pattern: /{id_facture}/search
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:searchArticle }

facture_update_total:
  pattern: /{id_facture}/updateTotal
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:updateFactureTotal }
  
facturation_article_add:
  pattern: /{id_facture}/article_add/{id_article}
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:addArticle }
  
facture_article_update_quantite:
  pattern: /{id_fact_article}/update
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:updateArticleQuantite }

facture_article_remove:
  pattern: /{id_fact_article}/removeArticle
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:removeArticle }