facture:
  pattern: /
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:indexFacture }

facture_show:
  pattern: /{id}/show
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:showFacture }
  
facture_new:
  pattern: /new
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:newFacture }

facture_edit:
  pattern: /{id}/edit
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:editFacture }

facture_delete:
  pattern: /{id}/delete
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:deleteFacture }

facture_commit:
  pattern: /{id}/commit
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:commitFacture }

facture_article_search:
  pattern: /{id_facture}/articleSearch
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:searchArticle }

facture_client_search:
  pattern: /{id_facture}/clientSearch
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:searchClient }

facture_update_total:
  pattern: /{id_facture}/updateTotal
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:updateFactureTotal }
  
facturation_article_add:
  pattern: /{id_facture}/article_add/{id_article}
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:addArticle }

facturation_client_add:
  pattern: /{id_facture}/client_add/{id_client}
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:addClient }
    
facture_article_update_quantite:
  pattern: /{id_fact_article}/update
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:updateArticleQuantite }

facture_article_remove:
  pattern: /{id_fact_article}/removeArticle
  defaults: { _controller: BoutiqueGestionStockBundle:Facturation:removeArticle }