fournisseur:
    pattern:  /
    defaults: { _controller: "BoutiqueGestionStockBundle:Fournisseur:index" }

fournisseur_show:
    pattern:  /{id}/show
    defaults: { _controller: "BoutiqueGestionStockBundle:Fournisseur:show" }

fournisseur_new:
    pattern:  /new
    defaults: { _controller: "BoutiqueGestionStockBundle:Fournisseur:new" }

fournisseur_create:
    pattern:  /create
    defaults: { _controller: "BoutiqueGestionStockBundle:Fournisseur:create" }
    requirements: { _method: post }

fournisseur_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BoutiqueGestionStockBundle:Fournisseur:edit" }

fournisseur_update:
    pattern:  /{id}/update
    defaults: { _controller: "BoutiqueGestionStockBundle:Fournisseur:update" }
    requirements: { _method: post }

fournisseur_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BoutiqueGestionStockBundle:Fournisseur:delete" }
    requirements: { _method: post }
