inventaire:
  pattern: /
  defaults: { _controller: BoutiqueGestionStockBundle:Inventaire:index }

inventaire_show:
  pattern: /{id}/show
  defaults: { _controller: BoutiqueGestionStockBundle:Inventaire:show }
  
inventaire_delete:
  pattern: /{id}/delete
  defaults: { _controller: BoutiqueGestionStockBundle:Inventaire:delete }

inventaire_new:
  pattern: /new
  defaults: { _controller: BoutiqueGestionStockBundle:Inventaire:new }

inventaire_edit:
  pattern: /{id}/edit
  defaults: { _controller: BoutiqueGestionStockBundle:Inventaire:edit }
  
inventaire_print_form:
  pattern: /{id}/printForm
  defaults: { _controller: BoutiqueGestionStockBundle:Inventaire:printForm }

inventaire_add_divers:
  pattern: /{id}/addDivers
  defaults: { _controller: BoutiqueGestionStockBundle:Inventaire:addDivers }
  
inventaire_remove_divers:
  pattern: /{id}/removeDivers
  defaults: { _controller: BoutiqueGestionStockBundle:Inventaire:removeDivers }
  
inventaire_article_update_quantite:
  pattern: /{id}/updateQuantite
  defaults: { _controller: BoutiqueGestionStockBundle:Inventaire:updateQuantite }
  
inventaire_clore:
  pattern: /{id}/clore
  defaults: { _controller: BoutiqueGestionStockBundle:Inventaire:clore }
  
inventaire_print:
  pattern: /{id}/printInv
  defaults: { _controller: BoutiqueGestionStockBundle:Inventaire:printInventaire }
  
inventaire_article_search:
  pattern: /{id_inventaire}/search
  defaults: { _controller: BoutiqueGestionStockBundle:Inventaire:searchArticle }